# ./docker-compose.yml
version: '3.3'
services:
  bot:
    build: .
    container_name: mockBot-discord
    stdin_open: true
    tty: true

    environment:
      - BOT_TOKEN

    volumes:
      - ./token:/code/tokens
    restart: always

